datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    url: ${JDBC_CONNECTION_STRING}

ebean:
  ddl:
    run: true
    generate: true
